### ISSUE TITLE
Replace arxiv-cli with arxiv library

### ISSUE THREAD

**Issue by mwatts15** [openworm/openworm-scholar#9]
The arxiv-cli package hasn't been well maintained: it has out-of-date dependencies that don't work on the latest versions of core libraries. The arxiv library, on the other hand, has recent updates. The goal of this task is to replace use of arxiv-cli with arxiv.

**Comment by VahidGh** [comment]
Using Semantic Scholar it is also possible to get results published on arXiv.
Some API call like this can do it:
https://api.semanticscholar.org/arXiv:1705.10311

As said before the API seems not mature enough for sending queries like search based on keywords, alerting, etc. via api (or maybe it does and I don't know how). But I'm pretty sure they will consider such capabilities as well.
 
Would be great if we could handle all our requirements using some api like this.
